In [1]:
import random
import numpy as np

倾向于使用numpy.random，可以产生随机数矩阵

## random 
> choice(self, seq)：随机选择一个元素

> expovariate(self, lambd): Exponential distribution.

> gauss(self, mu, sigma)：Gaussian distribution.

> lognormvariate(self, mu, sigma)

> randint(self, a, b)：返回[a, b]间的随机数

> sample(self, population, k)：随机抽取k个不同的元素

> seed(self, a=None, version=2)

> uniform(self, a, b)

> random(self)：生成[0.0, 1.0)间的随机数

In [2]:
random.choice([1,2,3,4])

3

In [3]:
random.sample([1,2,3,4],2)

[2, 3]

In [4]:
random.randint(3,10)

8

In [5]:
random.uniform(3,10)

3.753931961837586

In [6]:
random.random()

0.09262409923600146

## numpy.random 
> binomial(n, p, size=None)   

> choice(a, size=None, replace=True, p=None) 

> normal(mu,sigma,size) 

> randint(low, high=None, size=None)

> randn(d0, d1, ..., dn)：产生标准正太分布的样本值(d0,d1等为维度)

> random_sample(size=None)：产生[0.0, 1.0]之间的随机数

>  uniform(low=0.0, high=1.0, size=None)

In [2]:
np.random.choice(10,size=[2,2])

array([[4, 2],
       [8, 0]])

In [3]:
np.random.randint(5,10,size=[5,])

array([6, 7, 9, 7, 6])

In [4]:
np.random.random_sample(size=[10,])

array([0.27774298, 0.15927215, 0.6349325 , 0.65452126, 0.07985568,
       0.97141415, 0.93511974, 0.09834949, 0.88801879, 0.1167073 ])

In [5]:
np.random.randn(10)

array([ 0.57601162, -0.74501817,  0.87156297, -0.29976153, -1.70263799,
        0.78361833,  1.41117858, -1.70480198, -0.79386017, -0.02562445])