In [1]:
import numpy as np

# 数组属性
> .ndim ：维度 

> .shape ：各维度的尺度 （2，5） 

> .size ：元素的个数 10 

> .dtype ：元素的类型 dtype(‘int32’) 

# 创建数组

> arange(n) 

> empty(shape)：创建新数组，只分配内存空间但不填充任何值

> eye(N)和identity(N)：创建一个N*N的单位矩阵

> ones()或identity()：单位矩阵(identity为线代中的说法)

> zeros()：0矩阵

> full(shape,fill_value)：以给定shape创建数组，填充fill_value

> linspace(start,end,num,endpoint=True)：构建等差数列（endpoint：是否包含最终值）

> logspace(start, stop, num, endpoint=True, base=10.0)：构建等比数列

> meshgrid(x,y)：接受两个一维数组，返回两个二维矩阵（对应两个数组中所有(x,y)对）

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [6]:
np.linspace(1,3,9,endpoint=False)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778])

In [7]:
np.logspace(0,2,5,base=2)

array([1.        , 1.41421356, 2.        , 2.82842712, 4.        ])

In [49]:
points = np.arange(-3,3)
xs,ys = np.meshgrid(points,points)
xs

array([[-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2]])

In [50]:
ys

array([[-3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2]])

# 数组的维度变换
> .reshape(shape) 

> .resize(shape) 

> .swapaxes(ax1, ax2)：将两个维度调换 

> .flatten()：对数组进行降维，返回折叠后的一位数组

> .ravel()：可以添加参数，指定行和列的优先顺序（C和Fortran顺序）

In [10]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a.resize((4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# 数组的类型变换
> asarray()

> asmatrix()

> tolist()

> tostring()

# 数组的运算
> abs()和fabs() 

> sqrt(a) : 计算各元素的平方根 

> square(a): 计算各元素的平方 

> log(a),log10(a)和log2(a) : 计算各元素的自然对数、10、2为底的对数 

> ceil(a) 

> floor(a)

> modf(a) : 将数组各元素的小数和整数部分以两个独立数组形式返回 

> exp(a) 

> sign(a) : 计算各元素的符号值 1（+），0，-1（-） 

> maximum(a, b)

> minimum(a, b) 

> mod(a, b)

# 数组中的函数应用
> vectorize()：将输入参数为标量的函数转变为输入参数为数组的函数

> frompyfunc(function, shape, **kwargs)

In [28]:
def myfunc(a, b):
    if a > b:
        return a - b
    else:
        return a + b
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

In [29]:
def func(i,j):
    return (i+1)*(j+1)             #i,j为索引位置
np.fromfunction(func,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

# 数组元素的定位
> nonzero()：返回非0元素的索引

> where(condition,[x,y])：只给出条件，返回为真的元素索引；否则对应返回x或者y

> ix_()：整合不同数组，用于选取方形区域

In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.nonzero(a > 3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [31]:
x = np.arange(9).reshape(3, 3)
np.where(x < 5, x, -1)

array([[ 0,  1,  2],
       [ 3,  4, -1],
       [-1, -1, -1]])

In [32]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
arr[[1,5,7,2],[0,3,1,2]]
#选出元素(1,0) (5,3) (7,1) (2,2)

array([ 4, 23, 29, 10])

In [34]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]
#等同于 arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [36]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
ax,bx = np.ix_(a,b)
ax*bx

array([[16, 10,  8],
       [24, 15, 12],
       [32, 20, 16],
       [40, 25, 20]])

#  数组的排序、搜索与计数

> argmax和argmin

> average(a, axis=None, weights=None, returned=False)

> cumprod(a, axis=None)

> cumsum(a, axis=None)

> nansum,nancumsum和nancumprod：视NaNs为0

> delete(arr, obj, axis=None)

In [41]:
x = np.array([[0, 3, 2], [3, 2, 1]])
np.argsort(x, axis=0)

array([[0, 1, 1],
       [1, 0, 0]], dtype=int64)

In [39]:
a = np.array([[1,2,3], [4,5,6]])
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [40]:
np.cumsum(a,axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [38]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

# 矩阵运算
> dot(a, b, out=None)：矩阵乘法

In [42]:
A = np.array( [[1,1],[0,1]] )  
B = np.array( [[2,0],[3,4]] )  

In [43]:
A*B

array([[2, 0],
       [0, 4]])

In [45]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])