In [1]:
import numpy as np

# 创建数组

arange(n) 

empty(shape)：创建新数组，只分配内存空间但不填充任何值

eye(N)和identity(N)：创建一个N*N的单位矩阵

ones()或identity()：单位矩阵(identity为线代中的说法)

zeros()：0矩阵

full(shape,fill_value)：以给定shape创建数组，填充fill_value

linspace(start,end,num,endpoint=True)：构建等差数列（endpoint：是否包含最终值）

logspace(start, stop, num, endpoint=True, base=10.0)：构建等比数列

meshgrid(x,y)：接受两个一维数组，返回两个二维矩阵（对应两个数组中所有(x,y)对）

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [6]:
np.linspace(1,3,9,endpoint=False)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778])

In [7]:
np.logspace(0,2,5,base=2)

array([1.        , 1.41421356, 2.        , 2.82842712, 4.        ])

In [49]:
points = np.arange(-3,3)
xs,ys = np.meshgrid(points,points)
xs

array([[-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2]])

In [50]:
ys

array([[-3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2]])

# 数组处理程序

## 改变数组形状
reshape(shape) 

resize(shape) 

flatten()：对数组进行降维，返回折叠后的一位数组

ravel()：可以添加参数，指定行和列的优先顺序（C和Fortran顺序）

In [10]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a.resize((4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
np.arange(15).reshape(5,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
x = np.arange(12).reshape(3,4)
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
x.ravel("F")

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

## 类转置操作
swapaxes(a,axis1,axis2)：互换数组对的两个轴

ndarray.T:转置数组

transpose(a[,axes])：排列数组的尺寸

## 改变数组种类
asarray()：将输入转换为数组

asmatrix()

tolist()

tostring()

## 组合数组
concatenate((a1, a2, ...), axis=0)

hstack() 和 vstack()

r_和c_：辅助堆叠类(堆叠到row和column)

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [13]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
np.r_[arr1,arr2]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## 拆分数组
split(a, indices_or_sections, axis=0)
> indices_or_sections :数字或者1维数组（数字：等分；一维数组：指定分割处）

vsplit：沿行

hsplit：沿列

dsplit：沿第三轴

In [17]:
arr = np.arange(9)
np.split(arr,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [18]:
np.split(arr,[2,4,6])

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7, 8])]

## 平铺数组
repeat(a, repeats, axis=None)：axis默认扁平化

tile(A,reps) ：沿指定轴向堆叠数组副本，重复填充A reps次

repeat是以元素为单位，tile是以轴为单位，填充的结果不同

In [20]:
arr = np.random.randn(2,2)
arr

array([[1.18990474, 0.11622665],
       [1.68626   , 0.82976633]])

In [21]:
arr.repeat(2)

array([1.18990474, 1.18990474, 0.11622665, 0.11622665, 1.68626   ,
       1.68626   , 0.82976633, 0.82976633])

In [22]:
arr.repeat([1,2],axis=1)

array([[1.18990474, 0.11622665, 0.11622665],
       [1.68626   , 0.82976633, 0.82976633]])

In [23]:
np.tile(arr,2)

array([[1.18990474, 0.11622665, 1.18990474, 0.11622665],
       [1.68626   , 0.82976633, 1.68626   , 0.82976633]])

In [24]:
np.tile(arr,[3,2])

array([[1.18990474, 0.11622665, 1.18990474, 0.11622665],
       [1.68626   , 0.82976633, 1.68626   , 0.82976633],
       [1.18990474, 0.11622665, 1.18990474, 0.11622665],
       [1.68626   , 0.82976633, 1.68626   , 0.82976633],
       [1.18990474, 0.11622665, 1.18990474, 0.11622665],
       [1.68626   , 0.82976633, 1.68626   , 0.82976633]])

## 添加和删除元素
delete(a,obj[,axis])

insert(a,obj,values[,axis])：沿给定轴在给定索引之前插入值

append(a,values[,axis])：将值附加到数组的末尾

resize(a,new_shape)

unique(a[,return_index])：查看数组唯一元素

In [30]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## 重新排列元素
flip(m[,axis])：沿给定轴颠倒数组中元素的顺序

fliplr(m)：左右翻转数组

flipud(m)：上下翻转数组

roll(a,shift[,axis])：沿给定轴滚动数组元素

# 浮点错误处理
seterr()：设置如何处理浮点错误

geterr()：获取当前处理浮点错误的方法

seterrcall(func)：设置浮点错误回调函数或日志对象

# 数组函数应用
vectorize()：将输入参数为标量的函数转变为输入参数为数组的函数

fromfunction(function, shape)

In [28]:
def myfunc(a, b):
    if a > b:
        return a - b
    else:
        return a + b
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

In [2]:
def func(i,j):
    return (i+1)*(j+1)             #i,j为索引位置
np.fromfunction(func,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

# 索引相关

## 生成索引数组
nonzero()：返回非0元素的索引

where(condition,[x,y])：只给出条件，返回为真的元素索引；否则对应返回x或者y

ix_()：整合不同数组，用于选取方形区域

In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.nonzero(a > 3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [31]:
x = np.arange(9).reshape(3, 3)
np.where(x < 5, x, -1)

array([[ 0,  1,  2],
       [ 3,  4, -1],
       [-1, -1, -1]])

In [32]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
arr[[1,5,7,2],[0,3,1,2]]
#选出元素(1,0) (5,3) (7,1) (2,2)

array([ 4, 23, 29, 10])

In [34]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]
#等同于 arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [36]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
ax,bx = np.ix_(a,b)
ax*bx

array([[16, 10,  8],
       [24, 15, 12],
       [32, 20, 16],
       [40, 25, 20]])

# 输入和输出

## numpy二进制文件（NPY、NPZ）
load(file)：从.npy、.npz或pickle文件加载阵列或pickle对象

save(file,a)：将数组保存为NumPy.npy格式的二进制文件

savez(file,*args,**kwds)：将几个数组以未压缩的.npz格式保存到单个文件中

## 文本文件
loadtxt(fname[,dtype,comments,delimiter,…])：从文本文件加载数据

savetxt(fname,X[,fmt,delimiter,newline,…])：将数组保存到文本文件

fromregex(file,regexp,dtype[,encoding])：使用正则表达式解析从文本文件构造数组

fromstring(string[,dtype,count,sep])：从字符串中的文本数据初始化的新一维数组

# 数学函数
round(a[,decimals])

prod(a[,decimals])

sum(a[,decimals])

nanprod(a[,decimals]):将NaNs视为1

cumprod(a[,axis])：返回沿给定轴的元素的累加乘积

cumsum(a[,axis,])：返回沿给定轴的元素的累加和

diff(a[,n,axis])：计算沿给定轴的第n个离散差

log2(x,)：x的以2为底的对数

log1p(x)：返回元素加一个输入数组的自然对数

# 随机抽样(np.random)
random(size)：[0.0, 1.0)间的随机数

permutation(x)：随机排列序列

choice(a, size=None, replace=True, p=None)

rand(d0, d1, ..., dn)               

randn(d0, d1, ..., dn)：正态分布

randint(low, high=None, size=None) 

beta(a, b, size=None)    

binomial(n, p, size=None)：返回成功次数

chisquare(df, size=None)          

normal(loc=0.0, scale=1.0, size=None)

poisson(lam=1.0, size=None)  

In [34]:
np.random.binomial(100,0.5,4)

array([42, 50, 50, 40])

# 排序、搜索和计数

## 排序
sort(a, axis=-1, kind='quicksort', order=None) 

argsort(a, axis=-1, kind='quicksort', order=None)

lexsort(keys, axis=-1)：可以一次性对多个键数组进行间接排序，优先级为从后往前

In [35]:
values = np.array([5,0,1,3,2])
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [36]:
arr = np.random.randn(3,5)
arr

array([[-0.07568773, -2.49296142,  2.69851866, -0.70015304,  0.47493603],
       [ 0.61082613, -1.59783337, -0.13916357, -1.87432462,  0.57976661],
       [ 0.93548045, -2.29589544, -0.14344285,  0.49218697, -1.94532356]])

In [37]:
arr[:,arr[0].argsort()]

array([[-2.49296142, -0.70015304, -0.07568773,  0.47493603,  2.69851866],
       [-1.59783337, -1.87432462,  0.61082613,  0.57976661, -0.13916357],
       [-2.29589544,  0.49218697,  0.93548045, -1.94532356, -0.14344285]])

## 搜索
argmax(a[,axis])

nanargmax(a[,axis])	

argmin(a[,axis])	

nanargmin(a[,axis])	

argwhere(a)	

In [39]:
arr = np.arange(6)

In [41]:
arr.argmax()

5

## 计数
count_nonzero(a[,axis])

# 统计相关
percentile(a,q[,axis,])

quantile(a,q[,axis,out])

std(a[,axis])

nanstd(a[,axis])

var(a[,axis])

nanvar(a[,axis])

corrcoef(x[,y,rowvar,bias,ddof])：Pearson积矩相关系数

correlate(a,v[,mode])

cov(m[,y,rowvar,bias,ddof,fweights,…])

histogram(a[,bins,range,normed,weights,…])

bincount(x[,weights,minlength])

In [48]:
a = np.array([1,2,3])
b = np.array([4,3,4])

In [49]:
np.cov(a,b)

array([[1.        , 0.        ],
       [0.        , 0.33333333]])

In [50]:
np.corrcoef(a, b)

array([[1., 0.],
       [0., 1.]])