In [1]:
import numpy as np

## 创建array
### 常用
> empty(shape)：创建新数组，只分配内存空间但不填充任何值

> eye(N)和identity(N)：创建一个N*N的单位矩阵

> ones()：1矩阵

> zeros()：0矩阵

> full(shape,fill_value)：以给定shape创建数组，填充fill_value

In [2]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.ones((3,4))  

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.zeros((3,4))     

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

### 其它
> asarray()：将输入转化为array

> copy()

> tolist()

> tostring()

> arange()

> meshgrid()